use proy2;
DROP TABLE IF EXISTS temporal;
CREATE TABLE temporal(
    NOMBRE_ELECCION VARCHAR(50),
    YEAR_ELECCION VARCHAR(50),
    PAIS VARCHAR(50),
    REGION VARCHAR(50),
    DEPTO VARCHAR(50),
    MUNICIPIO VARCHAR(50),
    PARTIDO VARCHAR(50),
    NOMBRE_PARTIDO VARCHAR(50),
    SEXO VARCHAR(50),
    RAZA VARCHAR(50),
    ANALFABETOS VARCHAR(50),
    ALFABETOS VARCHAR(50),
    PRIMARIA VARCHAR(50),
    NIVEL_MEDIO VARCHAR(50),
    UNIVERSITARIOS VARCHAR(50)
);
SET GLOBAL local_infile=1;
LOAD DATA LOCAL INFILE './ICE-FUENTE-MEJORADO.csv'
INTO TABLE temporal
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ';'
ENCLOSED BY '\"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(NOMBRE_ELECCION,
YEAR_ELECCION,
PAIS,
REGION,
DEPTO,
MUNICIPIO,
PARTIDO,
NOMBRE_PARTIDO,
SEXO,
RAZA,
ANALFABETOS,
ALFABETOS,
PRIMARIA,
NIVEL_MEDIO,
UNIVERSITARIOS)
SET NOMBRE_ELECCION =TRIM(NOMBRE_ELECCION),
YEAR_ELECCION =TRIM(YEAR_ELECCION),
PAIS =TRIM(PAIS),
REGION =TRIM(REGION),
DEPTO =TRIM(DEPTO),
MUNICIPIO =TRIM(MUNICIPIO),
PARTIDO =TRIM(PARTIDO),
NOMBRE_PARTIDO =TRIM(NOMBRE_PARTIDO),
SEXO =TRIM(SEXO),
RAZA =TRIM(RAZA),
ANALFABETOS =TRIM(ANALFABETOS),
ALFABETOS =TRIM(ALFABETOS),
PRIMARIA =TRIM(PRIMARIA),
NIVEL_MEDIO =TRIM(NIVEL_MEDIO),
UNIVERSITARIOS =TRIM(UNIVERSITARIOS);

select count(*) from temporal;